common/models/Message.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "message".
 *
 * @property int $id
 * @property int $user_id
 * @property string $sender_name
 * @property string $sender_email
 * @property string $subject
 * @property string $content
 * @property int $processed
 *
 * @property User $user
 */
class Message extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        $x=true;
		if(!Yii::$app->user->getId()) $x=false;
		return [
            [['id'], 'integer'],
            [['user_id'], 'integer'],
            [['subject','content'], 'required'],
            [['content'], 'string'],
            [['sender_name','subject'], 'string', 'max' => 255],
            [['sender_email'], 'string', 'max' => 50],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common', 'Message ID'),
            'user_id' => Yii::t('common', 'User ID'),
            'sender_name' => Yii::t('common', 'Sender Name'),
            'sender_email' => Yii::t('common', 'Sender E-mail'),
            'subject' => Yii::t('common', 'Subject'),
            'content' => Yii::t('common', 'Content'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\MessageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\MessageQuery(get_called_class());
    }
}

backend/controllers/MessageController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Message;
use common\models\search\MessageSearch;
use backend\models\MessageAnswerer;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ServerErrorHttpException;

/**
 * MessageController implements the CRUD actions for Message model.
 */
class MessageController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Message models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MessageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Message model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Message model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Message();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Message model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Message model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
	
	/**
     * Marks an existing Message as processed.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionProcessed($id){
		$model = $this->findModel($id);
		$model->processed=1;
		$model->save();
		//return $this->redirect(['view', 'id' => $model->id]);
		return $this->redirect(['index']);
	}
	
	public function actionAnswer($id){
		$model=$this->findModel($id);
		$ma=new MessageAnswerer();
		if ($ma->load(Yii::$app->request->post()) && $ma->validate()) {
			if(!($ma->sendEmail(Yii::$app->params['adminEmail']))) throw new ServerErrorHttpException(Yii::t('common', 'Could not send an e-mail with the answer.'));
			$model->processed=1;
			$model->save();
			return $this->redirect(['index']);
		}
		//else throw new ServerErrorHttpException(Yii::t('common', 'Could not send an e-mail with the answer.'));
		return $this->render('answer', [
            'model' => $model,
			'ma'	=> $ma,
        ]);
	}
	
    /**
     * Finds the Message model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Message the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Message::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('common', 'The requested page does not exist.'));
    }
}

backend/views/message/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Message */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="message-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'sender_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'sender_email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/message/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\MessageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="message-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'sender_name') ?>

    <?= $form->field($model, 'sender_email') ?>

    <?= $form->field($model, 'subject') ?>

    <?php // echo $form->field($model, 'content') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('common', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('common', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/message/answer.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\DetailView;

$this->title = Yii::t('common', 'Answer the message no. ').$model->id;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="answer">
    <h1><?= Html::encode($this->title) ?></h1>
	
	<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'user_id',
            ['attribute' => 'created_by',
            'value' => ($model->user_id>0)?$model->user->username:''],
            'sender_name',
			'sender_email:email',
            'subject',
            'content:ntext',
			['attribute' => 'processed',
            'value' => ($model->processed==1)?Yii::t('common', 'Yes'):Yii::t('common', 'No')],
        ],
    ]) ?>
	
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'answer-form']); ?>

               <?= $form->field($ma, 'body')->textarea(['rows' => 6,'autofocus' => true]) ?>
			   
			   <?= $form->field($ma, 'mid')->hiddenInput(['value'=>$model->id])->label(false) ?>

                <div class="form-group">
                    <?= Html::submitButton(Yii::t('common', 'Send'), ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

backend/views/message/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Message */

$this->title = Yii::t('common', 'Create Message');
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Messages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="message-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/message/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\MessageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common', 'Messages');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="message-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('common', 'Create Message'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
		'rowOptions' => function ($model, $index, $widget, $grid){
			if($model->processed == 1) return ['class' => 'gray'];
			else return [];
		},
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'user_id',
            //'sender_name',
			[
				'attribute' => 'created_by',
				'value' => function ($model) {
                    return ($model->user_id>0)?$model->user->username:'';
                },
			],
            'sender_email:email',
            'subject',
            //'content:ntext',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => Yii::t('common', 'Actions'),
                'template' => '{view}	{update}	{delete}	{answer}	{processed}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'title' => Yii::t('common', 'View'),
                        ]);
                    },
        
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('common', 'Update'),
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('common', 'Delete'),
                        ]);
                    },
					'answer' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-send"></span>', $url, [
                                    'title' => Yii::t('common', 'Answer'),
                        ]);
                    },
					'processed' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-check"></span>', $url, [
                                    'title' => Yii::t('common', 'Mark as processed'),
                        ]);
                    }
      
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        return Url::to(['/message/view','id'=>$model->id]);
                    }
                    if ($action === 'update') {
                        return Url::to(['/message/update','id'=>$model->id]);
                    }
                    if ($action === 'delete') {
                        return Url::to(['/message/delete','id'=>$model->id]);
                    }
					if ($action === 'answer') {
                        return Url::to(['/message/answer','id'=>$model->id]);
                    }
					if ($action === 'processed') {
                        return Url::to(['/message/processed','id'=>$model->id]);
                    }
                },
            ],
        ],
    ]); ?>
</div>

backend/views/message/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Message */

$this->title = Yii::t('common', 'Update Message: ' . $model->id, [
    'nameAttribute' => '' . $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Messages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('common', 'Update');
?>
<div class="message-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/message/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Message */

$this->title = Yii::t('common', 'Message no. ').$model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Messages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="message-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('common', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('common', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('common', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
		<?= Html::a(Yii::t('common', 'Mark as processed'), ['processed', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
		<?= Html::a(Yii::t('common', 'Answer'), ['answer', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'user_id',
            ['attribute' => 'created_by',
            'value' => ($model->user_id>0)?$model->user->username:''],
            'sender_name',
			'sender_email:email',
            'subject',
            'content:ntext',
			['attribute' => 'processed',
            'value' => ($model->processed==1)?Yii::t('common', 'Yes'):Yii::t('common', 'No')],
        ],
    ]) ?>

</div>