common/models/Major.php
<?php

namespace common\models;

use Yii;
use common\models\File;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\data\ActiveDataProvider;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yz\shoppingcart\CartPositionTrait;
use yz\shoppingcart\CartPositionInterface;

/**
 * This is the model class for table "major".
 *
 * @property int $id
 * @property int $university_id
 * @property string $name
 * @property int $price
 * @property int $tax
 * @property string $description
 * @property int $active
 * @property int $created_by
 * @property string $created_at
 * @property int $updated_by
 * @property string $updated_at
 *
 * @property OrderMajor[] $orderMajors
 * @property University $university
 * @property User $createdBy
 * @property User $updatedBy
 */
class Major extends ActiveRecord implements CartPositionInterface
{
    use CartPositionTrait;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'major';
    }
    
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    // ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                // if you're using datetime instead of UNIX timestamp:
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'attributes' => [
                    // ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_by'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['university_id', 'name', 'price', 'tax'], 'required'],
            [['id', 'university_id', 'price', 'tax', 'active', 'created_by', 'updated_by'], 'integer'],
            [['university_id'], 'compare', 'operator' => '>', 'compareValue' => 0],
            [['name', 'description'], 'string'],
            [['created_at', 'updated_at'], 'default', 'value' => date('Y/m/d')],
            [['created_by', 'updated_by'], 'default', 'value' => Yii::$app->user->getId(true)],
            [['active'], 'default', 'value' => 1],
            [['tax'], 'default', 'value' => 23],
            [['created_at', 'updated_at'], 'safe'],
            [['id'], 'unique'],
            [['university_id'], 'exist', 'skipOnError' => true, 'targetClass' => University::className(), 'targetAttribute' => ['university_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common', 'ID'),
            'university_id' => Yii::t('common', 'University ID'),
            'name' => Yii::t('common', 'Name'),
            'price' => Yii::t('common', 'Price'),
            'tax' => Yii::t('common', 'Tax'),
            'description' => Yii::t('common', 'Description'),
            //'availability' => Yii::t('common', 'Availability'),
            //'thumbnail' => Yii::t('common', 'Thumbnail'),
            'active' => Yii::t('common', 'Active'),
            'created_by' => Yii::t('common', 'Created By'),
            'created_at' => Yii::t('common', 'Created At'),
            'updated_by' => Yii::t('common', 'Updated By'),
            'updated_at' => Yii::t('common', 'Updated At'),
        ];
    }
    
    public function getSubjectsProvider($id){
        $query=Subject::find()->where(['major_id' => $id]);
        $provider=new ActiveDataProvider([
            'query' => $query,
            'sort' => false,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        return $provider;
    }

    public function getFilesProvider($id){
        $query=File::find()->where(['major_id' => $id]);
        $provider=new ActiveDataProvider([
            'query' => $query,
            'sort' => false,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        return $provider;
    }

    // CartPositionInterface:
    public function getPrice()
    {
        return $this->price + $this->price * $this->tax / 100;
    }


    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderMajors()
    {
        return $this->hasMany(OrderMajor::className(), ['major_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUniversity()
    {
        return $this->hasOne(University::className(), ['id' => 'university_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\MajorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\MajorQuery(get_called_class());
    }
}

backend/controllers/MajorController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Major;
use common\models\PayU;
use common\models\search\MajorSearch;
use yii\helpers\Json;
// use common\models\query\SubjectQuery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MajorController implements the CRUD actions for Major model.
 */
class MajorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Major models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MajorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination=[
            'pageSize' => 20,
        ];
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Major model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $object = $this->findModel($id);
        $subjects=$object->getSubjectsProvider($id);
        $files=$object->getFilesProvider($id);
        
        return $this->render('view', [
            // przesłanie zmiennych do templatki jak w phpBB:
            'model' => $object,
            'subjects' => $subjects,
            'files' => $files,
        ]);
    }

    /**
     * Creates a new Major model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Major();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Major model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Major model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Major model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Major the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Major::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }
}

frontend/controllers/MajorController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Major;
use common\models\UserPermissions;
use common\models\search\MajorSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * MajorController implements the CRUD actions for Major model.
 */
class MajorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create','update','delete'],
                'rules' => [
                    [
                        'actions' => ['create','update','delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
			'statistics' => [
				'class' => \Klisl\Statistics\AddStatistics::class,
				'actions' => ['index','view'],
			],
        ];
    }

    /**
     * Lists all Major models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MajorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination=[
            'pageSize' => 20,
        ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Major model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $object = $this->findModel($id);
        $subjects=$object->getSubjectsProvider($id);
        $files=$object->getFilesProvider($id);
        $uid=Yii::$app->user->getId(true);
		// commented out as we decided to show files:
        /*if($object->createdBy && $uid==$object->createdBy->id) $permission=true;
        else{
            $connection = Yii::$app->getDb();
            $command=$connection->createCommand('SELECT expires FROM '.UserPermissions::tableName().' WHERE major_id='.$id.' AND user_id='.$uid);
            $result=$command->queryAll();
            $permission=ArrayHelper::map($result,'expires','expires');
            if(empty($permission)) $permission=false;
            else {
                $expires=array_pop($permission);
                if(!$expires) $permission=false;
				else if(time()>$expires){
					$permission=false;
					// remove an obsolete record from the DB:
					$command=$connection->createCommand('DELETE FROM '.UserPermissions::tableName().' WHERE major_id='.$id.' AND user_id='.$uid);
            		$result=$command->execute();
				}
                else $permission=true;
            }
        }*/
        return $this->render('view', [
            // przesłanie zmiennych do templatki jak w phpBB:
            'model' => $object,
            'subjects' => $subjects,
            'files' => $files,
            //'permission' => $permission,
        ]);
    }

    /**
     * Creates a new Major model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Major();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Major model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
		
		if($model->createdBy && $model->createdBy->id==Yii::$app->user->getId(true)){
			return $this->render('update', [
				'model' => $model,
			]);
		} else throw new ForbiddenHttpException(Yii::t('common', 'You have no access to this page.'));
    }

    /**
     * Deletes an existing Major model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        // $this->findModel($id)->delete();
        // return $this->redirect(['index']);
        throw new ForbiddenHttpException(Yii::t('common', 'You have no access to this page.'));
    }

    /**
     * Finds the Major model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Major the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Major::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }
}

frontend/views/major/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use common\models\University;

/* @var $this yii\web\View */
/* @var $model common\models\Major */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="major-form">

    <?php $form = ActiveForm::begin(); ?>

    <!-- <?= $form->field($model, 'id')->textInput() ?> -->

    <?php    
    $univs=University::find()->select("id,name")->all();
    $univs=ArrayHelper::map($univs,'id','name');
    $univs[0]='-----'; // it is safe as no index is less than 1;
    ksort($univs);
    //var_dump($univs);
    //die();
    ?>
    <?= $form->field($model, 'university_id')->dropDownList($univs) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput() ?>

    <?= $form->field($model, 'tax')->textInput() ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <!-- <?= $form->field($model, 'active')->textInput() ?> -->

    <!-- <?= $form->field($model, 'created_by')->textInput() ?> -->

    <!-- <?= $form->field($model, 'created_at')->textInput() ?> -->

    <!-- <?= $form->field($model, 'updated_by')->textInput() ?> -->

    <!-- <?= $form->field($model, 'updated_at')->textInput() ?> -->

    <div class="form-group">
        <?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/major/_item.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;


?>

<div class="col-sm-6">
	<h3><a href="<?= Url::to(['view', 'id'=> $model->id]) ?>"><?= $model->name ?></a></h3>

	<div><?= Yii::$app->formatter->asDecimal($model->price, 2) ?> zł</div>

	<?= Html::a("Dodaj", Url::to(['/cart/add-to-cart', 'id' => $model->id]), ['class' => 'btn btn-success']) ?>
</div>

frontend/views/major/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\MajorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="major-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'university_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'price') ?>

    <?= $form->field($model, 'tax') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'active') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('common', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('common', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/major/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Major */

$this->title = Yii::t('common', 'Create Major');
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Majors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="major-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/major/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\search\MajorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common', 'Majors');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="major-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('common', 'Create Major'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            [
                'attribute' => 'name',
                'label' => Yii::t('common', 'Major Name'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a($model->name, Url::to(['/major/view','id'=>$model->id]));
                },
            ],
            // replace the id with the name:
            [
                'attribute' => 'university.name',
                'label' => Yii::t('common', 'University Name'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a($model->university->name, Url::to(['/university/view','id'=>$model->university->id]));
                },
            ],
            'price',
            'tax',
            //'description:ntext',
            //'active',
            //'created_by',
            //'created_at',
            //'updated_by',
            //'updated_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => Yii::t('common', 'Actions'),
                //'headerOptions' => ['style' => 'color:#337ab7'],
                // 'template' => '{view}{update}{delete}',
                'template' => '{view}   {update}    {buy}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'title' => Yii::t('common', 'View'),
                        ]);
                    },
        
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('common', 'Update'),
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('common', 'Delete'),
                        ]);
                    },
                    'upload' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-upload"></span>', $url, [
                                    'title' => Yii::t('common', 'Upload'),
                        ]);
                    },
                    'buy' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-shopping-cart"></span>', $url, [
                                    'title' => Yii::t('common', 'Buy'),
                        ]);
                    },
      
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        return Url::to(['/major/view','id'=>$model->id]);
                    }
                    if ($action === 'update') {
                        return Url::to(['/major/update','id'=>$model->id]);
                    }
                    if ($action === 'delete') {
                        return Url::to(['/major/delete','id'=>$model->id]);
                    }
                    if ($action === 'buy') {
                        return Url::to(['/cart/add-to-cart','id'=>$model->id]);
                    }
                    if ($action === 'upload') {
                        return Url::to(['/file/create','sid'=>$model->id]);
                    }
                }
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

frontend/views/major/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Major */

$this->title = Yii::t('common', 'Update Major: ' . $model->name, [
    'nameAttribute' => '' . $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Majors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('common', 'Update');
?>
<div class="major-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/major/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model common\models\Major */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Majors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="major-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('common', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <!-- <?= Html::a(Yii::t('common', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('common', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?> -->
        <?= Html::a(Yii::t('common', 'Upload'), ['/file/create', 'mid' => $model->id], ['class' => 'btn btn-warning']) ?>
		<?= Html::a(Yii::t('common', 'Buy'), ['/cart/add-to-cart', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'id',
            ['attribute' => 'university_id',
            'value' => $model->university->name],
            'name:ntext',
            'price',
            'tax',
            'description:ntext',
        ],
    ]) ?>

    <br/>
    
    <h3><?php echo Yii::t('common', 'Subjects'); ?></h3>

    <?= GridView::widget([
        'dataProvider' => $subjects,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'name',
            [
                'label' => Yii::t('common', 'Name'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a($model->name, Url::to(['/subject/view','id'=>$model->id]));
                },
            ],
            ['attribute' => 'major.name',
            'value' => 'major.name'],
            'description:ntext',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => Yii::t('common', 'Actions'),
                //'headerOptions' => ['style' => 'color:#337ab7'],
                // 'template' => '{view}{update}{delete}',
                'template' => '{view}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'title' => Yii::t('common', 'View'),
                        ]);
                    },
        
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('common', 'Update'),
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('common', 'Delete'),
                        ]);
                    }
      
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        return Url::to(['/subject/view','id'=>$model->id]);
                    }
      
                    if ($action === 'update') {
                        return Url::to(['/subject/update','id'=>$model->id]);
                    }
                    if ($action === 'delete') {
                        return Url::to(['/subject/delete','id'=>$model->id]);
                    }
      
                }
            ],
        ],
    ]) ?>

    <br/>
    <h3><?php echo Yii::t('common', 'Files'); ?></h3>

    <?= GridView::widget([
        'dataProvider' => $files,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'name',
            [
                'label' => Yii::t('common', 'Name'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a($model->name, Url::to(['/file/view','id'=>$model->id]));
                    // return Url::to(['/subject/view','id'=>$model->id]);
                },
            ],
            'created_at',
            'created_by',
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => Yii::t('common', 'Actions'),
                //'headerOptions' => ['style' => 'color:#337ab7'],
                // 'template' => '{view}{update}{delete}',
                'template' => '{view}   {download}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'title' => Yii::t('common', 'View'),
                        ]);
                    },
        
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('common', 'Update'),
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('common', 'Delete'),
                        ]);
                    },
                    'download' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-download"></span>', $url, [
                                    'title' => Yii::t('common', 'Download'),
                        ]);
                    },
      
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        return Url::to(['/file/view','id'=>$model->id]);
                    }
                    if ($action === 'update') {
                        return Url::to(['/file/update','id'=>$model->id]);
                    }
                    if ($action === 'delete') {
                        return Url::to(['/file/delete','id'=>$model->id]);
                    }
                    if ($action === 'download') {
                        return Url::to(['/file/download','id'=>$model->id]);
                    }
                }
            ],
        ],
    ]) ?>
</div>